### Register a new user
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}

### Register the same user again (should fail)
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}
### Login a user (SUCCESS)
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}

### Login a user (FAIL - Wrong Password)
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaErrada"
}