### Register a new user
POST https://agriplanum.onrender.com/api/register
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}

### Register the same user again (should fail)
POST https://agriplanum.onrender.com/api/register
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}

### Login a user (SUCCESS)
POST https://agriplanum.onrender.com/api/login
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaForte123"
}

### Login a user (FAIL - Wrong Password)
POST https://agriplanum.onrender.com/api/login
Content-Type: application/json

{
    "email": "meuprimeirousuario@email.com",
    "password": "senhaErrada"
}
